# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/databases.json
Databases:
  my_store:
    Url: jdbc:hsqldb:mem:my_store
    Driver: org.hsqldb.jdbc.JDBCDriver
    Password: ${decrypt:}
